services:
  zkp2p-indexer-postgres:
    container_name: zkp2p-indexer-postgres
    image: postgres:16
    shm_size: 16g
    command: postgres -c 'max_connections=500' -c work_mem=256MB -c maintenance_work_mem=256MB -c max_wal_size=1GB
    ports:
      - 42070:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - zkp2p
    environment:
      - POSTGRES_DB=zkp2p
      - POSTGRES_USER=zkp2p
      - POSTGRES_PASSWORD=password

networks:
  zkp2p:
    driver: bridge

volumes:
  zkp2p:
    external: true
