services:
  zkp2p-indexer-postgres:
    container_name: zkp2p-indexer-postgres
    image: postgres:16
    shm_size: 16g
    command: postgres -c 'max_connections=500' -c work_mem=256MB -c maintenance_work_mem=256MB -c max_wal_size=1GB
    ports:
      - 42070:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - zkp2p
    environment:
      - POSTGRES_DB=zkp2p
      - POSTGRES_USER=zkp2p
      - POSTGRES_PASSWORD=password

  zkp2p-indexer:
    container_name: zkp2p-indexer
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 13072:13072
    volumes:
      - ./abis:/app/abis
      - ./src:/app/src
      - ./tsconfig.json:/app/tsconfig.json
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./ponder.config.ts:/app/ponder.config.ts
      - ./ponder-env.ts:/app/ponder-env.ts
      - ./ponder.schema.ts:/app/ponder.schema.ts
    networks:
      - zkp2p
    environment:
      - PONDER_RPC_URL_369=https://rpc.pulsechain.com
      - DATABASE_URL=postgres://zkp2p:password@zkp2p-indexer-postgres/zkp2p
      - DATABASE_SCHEMA=zkp2p

networks:
  zkp2p:
    driver: bridge

volumes:
  zkp2p:
    external: true
